# LOGGING
logging:
  file: build/planejamento-digital.log
  level:
    br.una: INFO
    org.springframework: WARN
    org.hibernate: WARN

# DATABASE
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
      password.secret: ${PASSWORD_SECRET}
