# APPLICATION
spring:
  application:
    name: Planejamento Digital
    description: Projeto exemplo da disciplina tecnologias para aplicações web.
    version: @project.version@
  profiles:
    active: dev

# SERVER
server:
  contextPath: /
  port: 8080
