# LOGGING
logging:
  file: build/planejamento-digital.log
  level:
    br.una: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# DATABASE - Vamos usar depois
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/plan_digital
#    username: postgres
#    password: admin
#    driverClassName: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  security:
#      password.secret: secret
spring:
  datasource:
    url: jdbc:h2:mem:plan_digital;INIT=runscript from 'classpath:schema-h2.sql'\;runscript from 'classpath:data-h2.sql'
    username: h2
    password: h2
    initialize: true
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: none